dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "7.9.0"
before_install:
  - npm install truffle@3.2.1 -g
  - npm i -g ethereumjs-testrpc
  - npm install
  - truffle install zeppelin
script:
  - testrpc > /dev/null &
  - truffle test
